server.port=8899
spring.application.name=spring-ai-deepseek-demo

spring.ai.dashscope.api-key=sk-ws-H.ERRIEHY.RIYt.MEYCIQDJx2AWsrUzuO-vem06pqt7qGWeDSUbmkSJ55XpX9gJoAIhAKPlT10PN5oSBAL-VfHyKQUn_vQcqfjuJUx67ZrkGcjY